#Life Expectancy Prediction
 Group Members : Vedant Mukhedkar, Kiran Fartade, Atharva Mahajan

In [ ]:
import pandas as pd
import numpy as np
 
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import MinMaxScaler
import math
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Life Expectancy Data.csv')

In [ ]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

#EDA

In [ ]:
df.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

In [ ]:
df.shape

(2938, 22)

In [ ]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [ ]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [ ]:
df.fillna(value = df.mean(), inplace = True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

In [ ]:
df.corr()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
Year,1.000000,0.169623,-0.078861,-0.037415,-0.048168,0.031400,0.089398,-0.082493,0.108327,-0.042937,0.093820,0.081860,0.133853,-0.139741,0.093351,0.014951,-0.047592,-0.050627,0.236333,0.203471
Life expectancy,0.169623,1.000000,-0.696359,-0.196535,0.391598,0.381791,0.203771,-0.157574,0.559255,-0.222503,0.461574,0.207981,0.475418,-0.556457,0.430493,-0.019638,-0.472162,-0.466629,0.692483,0.715066
Adult Mortality,-0.078861,-0.696359,1.000000,0.078747,-0.190408,-0.242814,-0.138591,0.031174,-0.381449,0.094135,-0.272694,-0.110875,-0.273014,0.523727,-0.277053,-0.012501,0.299863,0.305366,-0.440062,-0.435108
infant deaths,-0.037415,-0.196535,0.078747,1.000000,-0.113812,-0.085612,-0.178783,0.501128,-0.227220,0.996629,-0.170674,-0.126564,-0.175156,0.025231,-0.107109,0.548522,0.465590,0.471228,-0.143663,-0.191757
Alcohol,-0.048168,0.391598,-0.190408,-0.113812,1.000000,0.339634,0.075447,-0.051055,0.318070,-0.110777,0.213744,0.294898,0.215242,-0.048650,0.318591,-0.030765,-0.416946,-0.405881,0.416099,0.497546
percentage expenditure,0.031400,0.381791,-0.242814,-0.085612,0.339634,1.000000,0.011679,-0.056596,0.228537,-0.087852,0.147203,0.173414,0.143570,-0.097857,0.888140,-0.024648,-0.251190,-0.252725,0.380374,0.388105
Hepatitis B,0.089398,0.203771,-0.138591,-0.178783,0.075447,0.011679,1.000000,-0.090317,0.134929,-0.184413,0.408519,0.050084,0.499958,-0.102405,0.062318,-0.109811,-0.105144,-0.108334,0.150992,0.171755
Measles,-0.082493,-0.157574,0.031174,0.501128,-0.051055,-0.056596,-0.090317,1.000000,-0.175925,0.507809,-0.136146,-0.104569,-0.141861,0.030899,-0.068060,0.236250,0.224742,0.221007,-0.115764,-0.122609
BMI,0.108327,0.559255,-0.381449,-0.227220,0.318070,0.228537,0.134929,-0.175925,1.000000,-0.237586,0.282156,0.231814,0.281059,-0.243548,0.276645,-0.063238,-0.532025,-0.538911,0.479837,0.508105
under-five deaths,-0.042937,-0.222503,0.094135,0.996629,-0.110777,-0.087852,-0.184413,0.507809,-0.237586,1.000000,-0.188703,-0.128269,-0.195651,0.038062,-0.110640,0.535864,0.467626,0.472099,-0.161533,-0.207111
Polio,0.093820,0.461574,-0.272694,-0.170674,0.213744,0.147203,0.408519,-0.136146,0.282156,-0.188703,1.000000,0.130129,0.673553,-0.159489,0.193980,-0.034882,-0.219938,-0.220710,0.355398,0.385832
Total expenditure,0.081860,0.207981,-0.110875,-0.126564,0.294898,0.173414,0.050084,-0.104569,0.231814,-0.128269,0.130129,1.000000,0.145597,-0.001383,0.121467,-0.066698,-0.268724,-0.275240,0.149095,0.218310
Diphtheria,0.133853,0.475418,-0.273014,-0.175156,0.215242,0.143570,0.499958,-0.141861,0.281059,-0.195651,0.673553,0.145597,1.000000,-0.164787,0.182795,-0.025458,-0.227820,-0.221105,0.371729,0.389944
HIV/AIDS,-0.139741,-0.556457,0.523727,0.025231,-0.048650,-0.097857,-0.102405,0.030899,-0.243548,0.038062,-0.159489,-0.001383,-0.164787,1.000000,-0.134514,-0.027318,0.203922,0.207140,-0.247454,-0.218620
GDP,0.093351,0.430493,-0.277053,-0.107109,0.318591,0.888140,0.062318,-0.068060,0.276645,-0.110640,0.193980,0.121467,0.182795,-0.134514,1.000000,-0.025612,-0.267745,-0.272400,0.440317,0.429489
Population,0.014951,-0.019638,-0.012501,0.548522,-0.030765,-0.024648,-0.109811,0.236250,-0.063238,0.535864,-0.034882,-0.066698,-0.025458,-0.027318,-0.025612,1.000000,0.236117,0.233941,-0.007951,-0.029465
thinness 1-19 years,-0.047592,-0.472162,0.299863,0.465590,-0.416946,-0.251190,-0.105144,0.224742,-0.532025,0.467626,-0.219938,-0.268724,-0.227820,0.203922,-0.267745,0.236117,1.000000,0.939102,-0.406662,-0.446140
thinness 5-9 years,-0.050627,-0.466629,0.305366,0.471228,-0.405881,-0.252725,-0.108334,0.221007,-0.538911,0.472099,-0.220710,-0.275240,-0.221105,0.207140,-0.272400,0.233941,0.939102,1.000000,-0.395779,-0.435777
Income composition of resources,0.236333,0.692483,-0.440062,-0.143663,0.416099,0.380374,0.150992,-0.115764,0.479837,-0.161533,0.355398,0.149095,0.371729,-0.247454,0.440317,-0.007951,-0.406662,-0.395779,1.000000,0.796207
Schooling,0.203471,0.715066,-0.435108,-0.191757,0.497546,0.388105,0.171755,-0.122609,0.508105,-0.207111,0.385832,0.218310,0.389944,-0.218620,0.429489,-0.029465,-0.446140,-0.435777,0.796207,1.000000

#Removing the less correlating features

In [ ]:
df = df.drop(['percentage expenditure', ' thinness 5-9 years', 'infant deaths'], axis = 1)

In [ ]:
df.shape

(2938, 19)

In [ ]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'Alcohol', 'Hepatitis B', 'Measles ', ' BMI ', 'under-five deaths ',
       'Polio', 'Total expenditure', 'Diphtheria ', ' HIV/AIDS', 'GDP',
       'Population', ' thinness  1-19 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [ ]:
df.head(20)

,Country,Year,Status,Life expectancy,Adult Mortality,Alcohol,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,0.01,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,0.01,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,0.01,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,0.01,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,0.01,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279.0,0.01,66.0,1989,16.7,102,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281.0,0.01,63.0,2861,16.2,106,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287.0,0.03,64.0,1599,15.7,110,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295.0,0.02,63.0,1141,15.2,113,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,0.415,8.4
9,Afghanistan,2006,Developing,57.3,295.0,0.03,64.0,1990,14.7,116,58.0,7.43,58.0,0.1,272.563770,2589345.0,19.2,0.405,8.1
10,Afghanistan,2005,Developing,57.3,291.0,0.02,66.0,1296,14.2,118,58.0,8.70,58.0,0.1,25.294130,257798.0,19.3,0.396,7.9
11,Afghanistan,2004,Developing,57.0,293.0,0.02,67.0,466,13.8,120,5.0,8.79,5.0,0.1,219.141353,24118979.0,19.5,0.381,6.8
12,Afghanistan,2003,Developing,56.7,295.0,0.01,65.0,798,13.4,122,41.0,8.82,41.0,0.1,198.728544,2364851.0,19.7,0.373,6.5
13,Afghanistan,2002,Developing,56.2,3.0,0.01,64.0,2486,13.0,122,36.0,7.76,36.0,0.1,187.845950,21979923.0,19.9,0.341,6.2
14,Afghanistan,2001,Developing,55.3,316.0,0.01,63.0,8762,12.6,122,35.0,7.80,33.0,0.1,117.496980,2966463.0,2.1,0.340,5.9
15,Afghanistan,2000,Developing,54.8,321.0,0.01,62.0,6532,12.2,122,24.0,8.20,24.0,0.1,114.560000,293756.0,2.3,0.338,5.5
16,Albania,2015,Developing,77.8,74.0,4.60,99.0,0,58.0,0,99.0,6.00,99.0,0.1,3954.227830,28873.0,1.2,0.762,14.2
17,Albania,2014,Developing,77.5,8.0,4.51,98.0,0,57.2,1,98.0,5.88,98.0,0.1,4575.763787,288914.0,1.2,0.761,14.2
18,Albania,2013,Developing,77.2,84.0,4.76,99.0,0,56.5,1,99.0,5.66,99.0,0.1,4414.723140,289592.0,1.3,0.759,14.2
19,Albania,2012,Developing,76.9,86.0,5.14,99.0,9,55.8,1,99.0,5.59,99.0,0.1,4247.614380,2941.0,1.3,0.752,14.2

In [ ]:
list1 = []
list1  = df.groupby('Country')['Life expectancy '].mean()

In [ ]:
list1

Country
Afghanistan                           58.19375
Albania                               75.15625
Algeria                               73.61875
Angola                                49.01875
Antigua and Barbuda                   75.05625
                                        ...
Venezuela (Bolivarian Republic of)    73.38750
Viet Nam                              74.77500
Yemen                                 63.86250
Zambia                                53.90625
Zimbabwe                              50.48750
Name: Life expectancy , Length: 193, dtype: float64

In [ ]:
list2 = []
list2  = df.groupby('Country')['Adult Mortality'].mean()
list2

Country
Afghanistan                           269.0625
Albania                                45.0625
Algeria                               108.1875
Angola                                328.5625
Antigua and Barbuda                   127.5000
                                        ...
Venezuela (Bolivarian Republic of)    163.0000
Viet Nam                              126.5625
Yemen                                 211.8125
Zambia                                354.3125
Zimbabwe                              462.3750
Name: Adult Mortality, Length: 193, dtype: float64

#Label encoding

In [ ]:
categ =  ['Country', 'Status', 'Life expectancy ', 'Adult Mortality',
       'Alcohol','Total expenditure','GDP',
       'Population', ' thinness  1-19 years',
       'Income composition of resources', 'Schooling']

from sklearn import preprocessing
le = preprocessing.LabelEncoder()

for i in categ:
  le.fit(df[i])
  le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
  print(le_name_mapping)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

categ = ['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'Alcohol','Total expenditure','GDP',
       'Population', ' thinness  1-19 years',
       'Income composition of resources', 'Schooling']

df[categ] = df[categ].apply(le.fit_transform)

In [ ]:
X = df[['Country', 'Year', 'Status','Adult Mortality',
       'Alcohol','Total expenditure','GDP',
       'Population', ' thinness  1-19 years',
       'Income composition of resources', 'Schooling']]
Y =  df['Life expectancy ']

In [ ]:
from sklearn.preprocessing import StandardScaler

#Standardizing the data

In [ ]:
#Standardize the dataset using standard scaler
scaler = StandardScaler()
scaler.fit(X)
scaled = scaler.transform(X)

#Train Test And Split of the data

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

#Implementing Linear Regression Model

In [ ]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [ ]:
print('Intercept =', model.intercept_)

In [ ]:
print('Coefficients = ', model.coef_)

In [ ]:
mse = mean_squared_error(y_test, y_pred)
mse

In [ ]:
r2score = r2_score(y_test, y_pred)
r2score

#Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestRegressor

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.35,random_state=0)

In [ ]:
forest_reg = RandomForestRegressor()
forest_reg.fit(x_train, y_train)

In [ ]:
forest_reg.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
y_pred=forest_reg.predict(x_test)
forest_reg.score(x_test,y_test)

#Predicting for user input function

In [ ]:
X_new = np.array([[75,7,33,55,56,15,43,6,8,40,1]])
#Prediction of the species from the input vector
prediction = forest_reg.predict(X_new)
print("Prediction of Species: {}".format(prediction))